title: Carlson Lin的个人博客
description: 欢迎访问我的个人博客
author: Carlson Lin
theme: minima
domain: linkaisheng.github.io
url: https://linkaisheng.github.io
baseurl: ""

# 自定义设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 社交链接
github_username: linkaisheng

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag 